# Generated by Django 2.0.7 on 2018-07-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfo',
            name='origin',
            field=models.CharField(blank=True, choices=[('osaa', '오사카'), ('tyoa', '도쿄'), ('bjsa', '베이징'), ('csha', '상하이'), ('tpet', '타이페이'), ('khh', '가오슝'), ('mfm', '마카오'), ('lpq', '루앙프라방'), ('vte', '비엔티엔'), ('bki', '코타키나발루'), ('kulm', '쿠알라룸프르'), ('pen', '페낭'), ('dad', '다낭'), ('sgn', '호치민'), ('han', '하노이'), ('dps', '발리'), ('cgki', '자카르타'), ('rep', '씨엠립'), ('pnh', '프놈펜'), ('bkkt', '방콕'), ('utp', '파타야'), ('syda', '시드니'), ('mela', '멜버른')], max_length=200),
        ),
    ]
