# Generated by Django 2.0.7 on 2018-07-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_ticket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightTicket',
        ),
        migrations.RemoveField(
            model_name='flightinfo',
            name='depart_date',
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='date',
            field=models.IntegerField(),
        ),
    ]
