# Generated by Django 2.0.7 on 2018-07-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_ticket', '0002_auto_20180720_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinfo',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_ticket.FlightInfo'),
        ),
    ]
