branch-defaults:
  dev:
    environment: Yourrealtrip-dev
    group_suffix: null
global:
  application_name: yourrealtrip
  branch: null
  default_ec2_keyname: fc-8th-p
  default_platform: Docker 18.03.1-ce
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: myrealtrip
  repository: null
  sc: git
  workspace_type: Application
